version: '3.9'

services:
  backend:
    image: postgres-sql-backend
    build:
      context: backend
      target: production

  frontend:
    image: postgres-sql-frontend
    build:
      context: frontend
      target: production
    environment:
      API_HOST_URI: ${POSTGRES_PLAYGROUND_API_HOST_URI}

  nginx:
    image: nginx:latest
    ports:
      - ${PORT:-8080}:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
