version: '3.9'

services:
  backend:
    build:
      context: backend
      target: development
    environment:
      PLAYGROUND_NETWORK: ${PLAYGROUND_NETWORK:-playground-network}
    volumes:
      - ./backend:/go/src/github.com/koyashiro/postgres-playground
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1323:1323

  frontend:
    build:
      context: frontend
      target: development
    environment:
      API_HOST_URI: ${POSTGRES_PLAYGROUND_API_HOST_URI}
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  redis:
    image: redis:latest

networks:
  default:
    name: ${PLAYGROUND_NETWORK:-playground-network}

volumes:
  node_modules:
