[package]
name = "rdbmspg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
axum = "0.5.6"
serde = "1.0.137"
# hyper = { version = "0.14.18", features = ["full"] }
tokio = { version = "1.18.2", features = ["full"] }
# tower = "0.4.12"
