[package]
name = "mysql-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["macros"] }
tonic = "0.7.2"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "mysql"] }
rdbms-gateway = { path = "../rdbms-gateway", features = ["mysql"] }
