name: Build and Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-image.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-image.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.7

      - name: Download dependencies
        working-directory: ./backend
        run: go mod download

      - name: Test
        working-directory: ./backend
        run: go test -v

  push_to_registry:
    name: Build and Publish Docker image to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rdbms-playground-backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./backend
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,scope=backend
          cache-to: type=gha,scope=backend,mode=max
