name: Build and Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-image.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-image.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.10.0

    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile

    - name: Check format
      working-directory: ./frontend
      run: yarn fmt:check

    - name: Lint
      working-directory: ./frontend
      run: yarn lint

    - name: Build
      working-directory: ./frontend
      run: yarn build

  push_to_registry:
    name: Build and Publish Docker image to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: rdbms-playground-frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./frontend
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
